"""Apply independently reviewed content corrections in memory, then export REV6.

The original REV5 and initial REV6 generator remain unchanged for traceability.
"""
from pathlib import Path

base=Path(__file__).resolve().parent/'build_ice2976_rev6.py'
source=base.read_text()
def replace(before,after):
    global source
    assert before in source, before[:120]
    source=source.replace(before,after)

replace("SOURCES[17]=", "SOURCES[1]=('Märklin','Nachrüstdecoder 60975/60976/60977','Stand 10/2025; S. 3-7 und 19; funktionierender Ersatzlink, identisch mit geprüfter lokaler Kopie','https://static.maerklin.de/damcontent/f5/a9/f5a967e35e5b3faa19d17d36c62f586a1762409392.pdf')\nSOURCES[22]=('Märklin','mDecoderTool3 Anleitung v3.60','S. 3: Informationen anzeigen und Einstellungen auslesen; keine garantierte UID-Anzeige','https://streaming.maerklin.de/public-media/mdt3/pdfs/D_mDecoderTool3_A5_v360.pdf')\nSOURCES[17]=")
replace('https://streaming.maerklin.de/public-media/cs2/cs2CAN-Protokoll-2_0.pdf','https://www.maerklin.de/fileadmin/media/service/software-updates/cs2CAN-Protokoll-2_0.pdf')
replace('Solange G0 offen ist, nur dokumentieren und spannungslos prüfen; den Zug nicht für diese Architektur zerlegen oder verdrahten.','Solange G0 offen ist, am ICE nur dokumentieren und spannungslos prüfen; den Zug nicht für diese Architektur zerlegen oder verdrahten. Davon getrennt dürfen A-C ausschließlich in bestätigten geeigneten Decoder-Prüfaufnahmen erfolgen.')
replace("step('B1','Bestand sichern.','Nur den 60977 an eine geeignete Märklin-Prüfaufnahme anschließen. Artikel, Firmware und eindeutigen CS3-Namen notieren. Bestehende Zentralendaten sichern, keine Lokliste zurücksetzen. Auslesen ist nicht Aktualisieren.')", "step('B1','60977 auslesen, nicht aktualisieren.','Nur den 60977 mit passendem Märklin-Aufbau am 60971 anschließen. Im mDecoderTool3: Decoder / Decoder-Informationen anzeigen. Typ und Firmware notieren. Dann Decoder / Decoder auslesen und Einstellungen als neues Projekt sichern; Sounds werden dabei nicht ausgelesen. Der Dialog ist kein garantierter UID-Leseweg. Nicht Decoder-Firmware aktualisieren auswählen.<super>22</super>')")
replace("step('B2','Master-Identität beschaffen.','Der Fachkundige dokumentiert die tatsächliche mfx-UID samt Herkunft. Märklins CAN-Dokument nennt .mfxuid in lokomotive.cs2. Das ist ein belegter Datenhinweis, aber hier keine verifizierte CS3-Klickfolge. Eine vorhandene Sicherung nur an einer Kopie untersuchen; nichts in die CS3 zurückschreiben.')", "step('B2','CS3 sichern, Identität klären.','In den CS3-Systemeinstellungen Sichern wählen, USB-Speicherort und neuen Dateinamen verwenden; nicht Wiederherstellen. Der Fachkundige untersucht nur eine Kopie: Enthält sie lokomotive.cs2 und zum eindeutig identifizierten 60977 das Feld .mfxuid? Dieses Feld ist für CS2 dokumentiert; Inhalt und Zuordnung der konkreten CS3-Sicherung sind noch zu prüfen. Nichts bearbeiten oder zurückspielen.<super>12,19</super>')")
replace('Hier endet die selbst ausführbare Einrichtung. Keine Werte ausprobieren. Erst belastbare Hersteller-/Fachbetriebsbestätigung plus realer Kombinationstest ermöglichen die Fortsetzung.','Keine Werte ausprobieren. B4 als getrennte, nur lesende Prüfung bleibt möglich. Erst mit belegter Identitätszuordnung B5 und C ausführen. Nur deren dokumentierter Erfolg gibt den weiteren ICE-Umbau frei.')
replace('refs(7,18,19)','refs(7,19,22)')
replace('Keine Gleisanschlussbox, Mobile-Station-Einspeisung oder Programmerausgänge an denselben Aufbau anschließen. Beide Decoder behalten getrennte Ausgangslasten.','Keine Gleisanschlussbox oder Programmerausgänge parallel anschließen. Aktiven mfx-Betrieb belegen; zufälliges Folgen unter DCC/MM zählt nicht. Protokolleinstellungen nur in der getrennten Testumgebung dokumentiert und rückstellbar ändern.')
replace('Vorbestehende Einträge nicht blind löschen.','Vorbestehende Einträge nicht blind löschen oder ausblenden. Ist der Slave weiter eigenständig angemeldet und unabhängig steuerbar, ist der Test nicht bestanden.')
replace('Nach geordnetem Ausschalten beide gemeinsam neu starten und C4 wiederholen. Danach Slave stromlos entfernen, wieder stromlos ergänzen und erneut testen.','Gemeinsam neu starten und C4 wiederholen. Danach am fachkundigen Prüfaufbau mit getrennter Einspeiseschaltung auch unterschiedliche Einschaltreihenfolgen prüfen. Keine Decoder unter Spannung stecken.')
replace('Fachkundig mit gesicherter Testumgebung oder separater Testzentrale prüfen. Keine produktive CS3-Lokliste für diesen Test löschen. Ohne diesen Versuch bleibt automatische Neuanmeldung ungeprüft.','Für G0 erforderlich: An einer Testzentrale, die den Master noch nicht kennt, automatisch anmelden und Slave-Folgen prüfen; danach Rückkehr zur CS3. Eine geänderte Adresse nur bei eigenem Nachweis als geprüft markieren. Ohne Nachweis G0 offen; keine produktiven Lokdaten löschen.')
replace('Eine vollständige isolierende Befestigung kann fachkundig ausgelegt werden, ist aber hier noch kein fertiger Ausweichplan: Schraubenschaft, Ring, Unterseite und Nachbarflächen müssen isoliert bleiben; ein erforderlicher Radmassepfad darf nicht verloren gehen. Nur eine Kunststoff-Unterlegscheibe oben reicht nicht. Keine unbestimmte Halter-Artikelnummer kaufen.','Fachkundiger Ausweichweg: vollständig isolierende Halterung mit isolierter Schraubenführung auslegen. Vor Verdrahtung beide zugänglichen Ringe gegen positiv bestätigtes Chassis prüfen: kein leitender Montagekontakt. Kontaktierung vorher/nachher positiv bestätigen. Danach Radmasse über das dokumentierte MASSE-Pad verdrahten; dieser Pfad zum Chassis ist erwünscht. Eine Kunststoffscheibe nur oben genügt nicht. Maße und Passung sind offen; dies ist keine Halter-Kaufempfehlung.')
replace("('Rückseite und Revision fehlen','Beschriftete Anschlussseite des eigenen Exemplars fehlt'),", "('Rückseite und Revision fehlen','Beschriftete Anschlussseite des eigenen Exemplars fehlt'),\n+('Vor Montage seine Funktion messen; weder Masse noch Isolation pauschal annehmen.','Vor Montage die Befestigungsfreigabe nach Kapitel 9 abschließen; einen unbekannten Ring weder als Masse noch als isoliert voraussetzen.'),".replace('\n+','\n'))
replace("page('12. Märklin-Träger im motorlosen Kopf')", """class SourceDiagram(Flowable):
    def __init__(self,path):
        Flowable.__init__(self); self.path=path; self.width=350; self.height=300
    def draw(self):
        with PILImage.open(self.path) as im: iw,ih=im.size
        # Clip the unchanged complete source image to its actual diagram.
        left,top,right,bottom=.055,.23,.49,.765
        sw=(right-left)*iw; sh=(bottom-top)*ih
        scale=min(self.width/sw,self.height/sh)
        c=self.canv; c.saveState(); q=c.beginPath(); q.rect(0,0,sw*scale,sh*scale); c.clipPath(q,stroke=0)
        c.drawImage(self.path,-left*iw*scale,-(1-bottom)*ih*scale,width=iw*scale,height=ih*scale)
        c.restoreState()

page('12. Märklin-Träger im motorlosen Kopf')""".replace('\n+','\n'))
replace("story.append(photo('/Users/martinwaelter/ICE Umbau/Arbeitsstand_REV10/bilder/ice2976_60977-p5-pads.jpg',W,300))", "story.append(SourceDiagram('/Users/martinwaelter/ICE Umbau/Arbeitsstand_REV10/bilder/ice2976_60977-p5-pads.jpg'))")
replace('Originalzeichnung aus Märklins 60977-Anleitung, S. 5, unverändert. Kein Foto des vorhandenen Trägers.','Vergrößerter Ausschnitt der unveränderten Originalzeichnung, Märklin-Anleitung S. 5. Kein Foto des vorhandenen Trägers; Positionen erst nach Übereinstimmungsprüfung verwenden.')
replace("page('12a. Hinteres Rot/Weiß eindeutig zuordnen')\nstory.append(Sketch('led'))", "page('12a. Hinteres Rot/Weiß eindeutig zuordnen')\nstory.append(Sketch('led'))\nadd('Beide ESU-Kästen sind derselbe hintere 59649: Plus an +Ub, oberer weißer Zweig über seinen Widerstand an LR, unterer roter Zweig an LV.','small')")
replace('ICE-Soundprojekt mit Märklin-Werkzeug einrichten, leise starten, mfx aktiv lassen.','ICE-Soundprojekt mit Märklin-Werkzeug einrichten, niedrige Anfangslautstärke konfigurieren; Soundprüfung erst in Schritt 52. mfx aktiv lassen.')
replace("step('49','Einstellungen wieder auslesen.','Geschriebene Identität, Sonderoption und Mapping mit dem gespeicherten Prüfprojekt vergleichen. Bei Abweichung die Verbindung nicht unter Spannung ausprobieren. Programmerzugang wird auch für spätere Korrekturen benötigt.')", "step('49','Gegen die richtigen Sollstände auslesen.','Jeden Decoder einzeln neu auslesen. Masteridentität und Synchronisationsoption mit G0 vergleichen. Endgültiges Mapping und Fahrzeugparameter mit dem separat vor dem Schreiben gespeicherten Fahrzeugprojekt vergleichen. Gewollte Änderungen gegenüber dem Prüfstandprojekt dokumentieren; bei unerklärter Abweichung nicht bestromen.')")
replace("step('50','Endgültige Funktionstabelle abnehmen.','F0 aus: beide Köpfe dunkel. F0 vorwärts: Motorseite weiß, Dummy rot. F0 rückwärts: Motorseite rot, Dummy weiß. Alle Zustände im Stand, Innenlicht und Sound unabhängig. Erst danach langsame reale Fahrtrichtung prüfen.')", "step('50','Sollzustände notieren, noch nicht bestromen.','F0 aus: beide Köpfe dunkel. F0 vorwärts: Motorseite weiß, Dummy rot. F0 rückwärts: Motorseite rot, Dummy weiß. Nur Konfiguration vorbereiten. Funktionstests nach den Freigaben in Kapitel 17: Hauptkopf Schritt 52, beide Köpfe Schritt 54. Fahrt ausschließlich Schritt 53; Innenlicht mit Wagen erst Schritt 56.')")
replace('Die vollständigen Vorproben, Isolationsmessungen und Nachproben nach 6a mit unveränderten Fahrzeugclips wiederholen. Dieselben passiven Pfade erneut messen.','Für Motoranschlüsse nur am Motortriebkopf: Folge 6a. Im Dummy keine Motorprobe: Zwei Punkte desselben abgetrennten Leiters und zwei Punkte des Metallbezugs jeweils positiv vorprüfen, Isolation messen, beide positiven Nachproben wiederholen. Serienwiderstand mit bekanntem Sollwert bewerten. Nicht durch LEDs messen oder freie Motorausgänge verbinden. Vor-/Nachproben im tatsächlich geschlossenen Gehäusezustand durchführen.')
replace("('Ist das nicht möglich, diese Prüfung fachkundig durchführen lassen.','Vier Hilfsprüfenden nach 6/6a erlauben die Vor-/Nachproben ohne Lösen der Fahrzeugclips. Ist das nicht möglich, diese Prüfung fachkundig durchführen lassen.')", "('Ist das nicht möglich, diese Prüfung fachkundig durchführen lassen.','Vier Hilfsprüfenden nach 6/6a erlauben die Vor-/Nachproben ohne Lösen der Fahrzeugclips. Ist das nicht möglich, diese Prüfung fachkundig durchführen lassen.'),\n('Keine Isolierfolie ohne Prüfung über wärmeabgebende Bauteile wickeln.','Decoder nicht mit Isolierband oder Isolierfolie einwickeln. Stattdessen gefährdende Metallflächen geeignet isolieren; Freiraum und Wärmeabfuhr erhalten.')")
replace("original('15. Den vorhandenen 60974 vorbereiten',[", "original('15. Den vorhandenen 60974 vorbereiten',[\n('vor erneutem Löten trennen und korrekt entladen.','vor erneutem Löten trennen. Anschlüsse nie zum Entladen kurzschließen. Solange Restspannung nicht fachgerecht ausgeschlossen ist, keine Lötarbeit.'),")
replace('Der ursprüngliche Direktlink zur 60977-Anleitung liefert beim Abruf teilweise HTTP 403. Die lokale Herstellerkopie ist vorhanden; insbesondere S. 4/5/7 wurden für Stecker, Pads und Einmessfahrt herangezogen. Fehlende Web-Erreichbarkeit ist kein Ersatz für die Prüfung des tatsächlich beiliegenden Dokuments.','Der frühere 60977-Direktlink lieferte HTTP 403. Der hier verwendete Ersatzlink wurde erneut geladen und per SHA-256 als identisch mit der geprüften Herstellerkopie bestätigt. S. 4/5/7 belegen Stecker, Pads und Einmessfahrt. Zusätzlich neue Bedienfolgen aus mDT3 S. 3 und CS3 S. 27 geprüft.')
replace('for n in range(11,22):','for n in range(11,23):')
replace('Die Gegenprüfung umfasst drei fokussierte Arbeitsbereiche: mfx-Architektur, Anschluss/Befestigung und Messlogik.','Drei fokussierte Entwurfsreviews prüften mfx-Architektur, Anschluss/Befestigung und Messlogik. Ein gefundener Reihenfolgefehler (zu früher Funktionstest) sowie Präzisierungen bei G0, Rücklesen, Dummy-Messung und Decoderisolation wurden korrigiert.')
exec(compile(source,str(base),'exec'),{'__file__':str(base),'__name__':'__main__'})
