"""Case-specific instructions applied to the fully corrected REV6 paragraph stream."""

REPLACEMENTS = [
('Prüffassung mit vorgezogenem Decoder-Nachweis und korrigierten Messkarten', 'Konkrete Arbeitsfassung für deinen ICE 2976 und deine vorhandenen Bauteile'),
('Offen bedeutet nicht widerlegt, aber auch nicht ausführungsreif.', 'Bei einem noch leeren Prüffeld ist auf der zugehörigen Seite angegeben, welches Foto, welche Messung oder welche Bestätigung du als Nächstes beschaffst.'),
('Kein improvisierter Tischaufbau', 'Für den Vorabtest: 60971 nur am 60977; ESU-Zugang zuerst beschaffen'),
('Decoder nicht lose auf Metall betreiben, keine nackten LEDs als Prüflast und keine unbestätigte Widerstandslast an den Motorausgang hängen. Beim Programmieren stets nur einen Decoder verbinden. Beim gemeinsamen Betriebstest nur eine Digitalquelle an beide Gleiseingänge; niemals Ausgänge oder Decoder-U+ parallel verbinden.', 'Lege den 60977 und den 59649 getrennt in ihre Verpackungen. Den 59649 nicht auf den Märklin 60971 stecken. Hast du keinen Zugang zu 53451 und zwei bestätigten Prüfaufnahmen, gib beide Decoder samt Kapitel A-C einem entsprechend ausgestatteten Fachbetrieb. Dort müssen die Gleiseingänge aus genau einer CS3 versorgt werden; Motor-, Licht-, Lautsprecher- und Plusanschlüsse der Decoder bleiben getrennt. Keine LED oder Drahtlast selbst als Prüfaufnahme improvisieren.'),
('Die exakte Zuordnung der Märklin-mfx-UID zu den beiden ESU-Eingabefeldern ist in den ausgewerteten Primärquellen nicht nachgewiesen. Keine Werte ausprobieren. B4 als getrennte, nur lesende Prüfung bleibt möglich. Erst mit belegter Identitätszuordnung B5 und C ausführen. Nur deren dokumentierter Erfolg gibt den weiteren ICE-Umbau frei.', 'Für deinen 60977 fehlen die belegten Eingabewerte für Hersteller-ID und Seriennummer im 59649. Sende dem Prüfenden das B1-Ausleseergebnis und die B2-Sicherungskopie; verlange beide ESU-Feldwerte samt Herkunft/Umrechnung schriftlich. Nicht 60977, 59649, eine DCC-Adresse oder ESUs Beispiel 151 eintragen. Bis die Zuordnung belegt ist, bleibt B5 gesperrt; B4 darf nur getrennt auslesen. Den ICE erst nach bestandenem C-Protokoll zerlegen.'),
('G0-STOPP: zentrale Lücke bleibt offen', 'G0: Noch keine Masterdaten in deinen 59649 schreiben'),
('Abbruch und Rückweg', 'Wenn C2-C7 scheitert: beide Decoder getrennt lassen'),
('Scheitert eine Pflichtfunktion, den Gesamtumbau für diese Architektur nicht beginnen. Gesicherte Konfigurationen erhalten, Fehlerfall protokollieren und klären lassen. Keine Traktion, DCC-Ersatzlösung oder Decoderneuanschaffung stillschweigend als Zielerfüllung einsetzen.', 'CS3 ausschalten und die Testaufnahmen von ihrer Gleisversorgung trennen. Den fehlgeschlagenen C-Schritt, die beiden Firmwarestände und die ausgelesene ESU-Sonderoption sichern; dem Prüfenden diese drei Angaben zusammen geben. Am ICE nichts ablöten. Keine Traktion anlegen und keine gleiche DCC-Adresse als bestandenen mfx-Test eintragen.'),
('STOPP - nie Widerstand an einem gespeisten Aufbau messen', 'Vor jeder Ohmmessung: ICE vom Gleis, beide Decoder und 60974 abgetrennt'),
('Alle Gleis- und Programmieranschlüsse physisch trennen. Beide Decoder und den Puffer abziehen. Ein geladener Puffer bleibt eine Spannungsquelle. Nicht kurzschließen, nicht mit dem Schraubendreher entladen. Bei unklarer Entladung zuerst Herstelleranweisung bzw. Fachbetrieb nutzen.', 'Nimm beide Triebköpfe und alle Wagen vom Gleis. Ziehe 60977 und 59649 aus ihren Trägern, nachdem alle Versorgungen getrennt sind. Deine beiden 60974 bleiben für diese Prüfungen außerhalb des Zuges. Einen bereits angeschlossenen Puffer weder weiterverwenden noch entladen, solange seine Restspannung nicht fachgerecht ausgeschlossen ist; seine Kontakte nicht überbrücken. Erst am so abgetrennten Aufbau auf Ω schalten.'),
('Widerstandsbereich wählen und Spitzen zusammenhalten.', 'Für kleine Durchgangswerte den Ω-Bereich wählen; für jede Isolationsprüfung Widerstands-Autorange oder den höchsten verfügbaren Ω-Bereich einstellen. Dann Spitzen zusammenhalten.'),
('Spitzen trennen. Das Gerät muss seinen offenen Zustand anzeigen, oft OL oder 1. Bedeutung anhand der eigenen Geräteanleitung klären. Danach nochmals zusammenhalten: Die Anzeige muss reproduzierbar wechseln.', 'Spitzen trennen und die Anzeige notieren. In deiner Geräteanleitung den Abschnitt Widerstandsmessung öffnen und prüfen, welches Zeichen Messbereichsüberschreitung/offen bedeutet (oft OL oder 1). Dieses Zeichen allein beweist in einem kleinen Ω-Bereich keine Isolation. Im höchsten Ω-Bereich beziehungsweise Autorange erneut trennen und zusammenhalten; beide Anzeigen müssen unterscheidbar bleiben.'),
('STOPP - Motor noch nicht an den Decoder', 'MOT_L und MOT_R an der LoDi 511 bleiben bis Ende Kapitel 6b unverbunden'),
('Ein übersehener Massekontakt an einer Bürste kann die Motorendstufe beschädigen. Die beiden Motorleitungen bleiben für die folgenden Prüfungen von der Platine getrennt. Keine Einmessfahrt und kein Versuch mit einem alten Analog-Umschaltimpuls.', 'Isoliere die freien Enden beider Motorleitungen einzeln. Weder diese Leitungen an MOT_L/MOT_R anlöten noch den 60977 einsetzen, bevor alle Messreihen aus 6a bestanden sind. Den alten Analogtrafo nicht zum Probieren benutzen. CV 7 und das Firmware-Versionsfeld nicht auf 77 ändern; dieser Wert aktiviert die Einmessfahrt.'),
('Zuerst spannungsfrei und ohne Elektronik', 'Prüfzustand: 60941 montiert, Motorleitungen abgelötet, Decoder draußen'),
('Zug vollständig vom Gleis nehmen. Beide Decoder, Puffer und sonstige Energiespeicher physisch abtrennen. Beide Motorleitungen von der übrigen Elektronik lösen. Unklar gespeicherte Energie nicht durch Zeitraten oder Kurzschließen beseitigen; nach Herstelleranweisung klären. Kein Widerstandstest an gespeister Elektronik.', 'Der ICE steht auf einer nichtleitenden Unterlage, nicht auf einem angeschlossenen Gleis. 60977 und 59649 sind abgezogen; beide 60974 liegen abgetrennt daneben. Verfolge jede der zwei Motorlitzen bis zum freien Ende: Keine darf noch an LoDi, Altplatine oder einer anderen Leitung hängen. Ein schon geladener Puffer gehört nicht in diesen Messaufbau. Keine Widerstandsmessung vornehmen, solange ein elektrischer Anschluss unklar ist.'),
('Die Metallteile der Clips dürfen keine Nachbarteile berühren.', 'Am 60941 darf PM1 nur seine Bürstenfahne und PM2 nur die andere berühren: nicht die benachbarte Schildschraube, Bürstenfeder oder Motorrahmenkante einklemmen.'),
('Ist eine sichere Befestigung nicht möglich, Prüfung fachkundig durchführen lassen.', 'Hält ein Clip nicht allein auf seiner vorgesehenen Metallfläche, nimm ihn ab und verwende einen kleineren isolierten Clip. Passt auch dieser nicht, fotografiere genau diese Stelle für den Prüfenden; den 60977 bis zur Messung abgezogen lassen.'),
('Multimeter: Schwarz COM, Rot V/Ω. Null-/Offenprobe nach Kapitel 2.', 'Multimeter: Schwarz COM, Rot V/Ω. Für diese Isolationsreihe Widerstands-Autorange oder höchsten Ω-Bereich wählen; Null-/Offenprobe nach Kapitel 2.'),
('Stabil offenen Zustand gemäß Messgeräteanleitung notieren. Jeder bleibende endliche Wert oder unklare Befund: STOPP.', 'Im höchsten Ω-Bereich/Autorange auf stabile Anzeige warten. Nur den bestätigten Offenwert notieren. Bei einem bleibenden Zahlenwert 60977 draußen lassen und Kapitel 7 ausführen; auch ein großer Widerstand ist kein bestandener OL-Befund.'),
('Eine fehlgeschlagene Nachprobe entwertet die Messreihe', 'PX-PX2 oder PM1-PM2 nachher offen? Alle sechs Messungen wiederholen'),
('OL schließt einen falschen Kondensator nicht aus', 'Am 60941 jeden Kondensatordraht verfolgen, auch wenn das Gerät OL zeigt'),
('Ein Kondensator von Bürste zu Metall kann sich beim Gleichstromtest aufladen und danach OL ergeben. Deshalb zusätzlich jeden Kondensator an beiden Enden verfolgen. Nur der bestätigte Quer-Kondensator M1-M2 bleibt im vorgesehenen Aufbau; siehe Kapitel 5 und 21.', 'Beginne an M1 und verfolge mit der Lupe jeden dort angelöteten Kondensatordraht bis zum zweiten Ende. Wiederhole das an M2. Endet er an der jeweils anderen Bürstenfahne, ist das der verbleibende Quer-Kondensator. Endet er am Motorrahmen, einer Masselötöse oder Schildschraube, diesen Kondensator bei abgetrenntem Motor auslöten. Verdecktes Ende zuerst sichtbar machen; nicht anhand seiner Farbe abschneiden. Danach 6a wiederholen.'),
('Die Stecklage muss am Index und an der tatsächlichen Platine bestimmt werden. Nicht allein „Bauteile oben“ als Regel verwenden.', '60977 abgezogen lassen. Am Steckfeld die fehlende Pinposition suchen und mit der blockierten Position der Decoderbuchse vergleichen. Beide müssen übereinander liegen; keine Stiftreihe seitlich versetzt ansetzen. Fehlt diese eindeutige Zuordnung, Nahfoto beider Steckseiten für den Abgleich aufnehmen.'),
('Unbestücktes großes Kontaktfeld. Nicht als SUSI-/Pufferbuchse verwenden. Das Foto liefert dafür keine Freigabe.', 'K1 ist das hier unbestückte Relaisfeld. An K1 wird in deinem Aufbau nichts angeschlossen. Insbesondere keinen 60974 und keinen vierpoligen Stecker darauf setzen.'),
('Beschrifteter Lautsprecherbereich. Vor Anschluss prüfen, dass die Pads tatsächlich zum vorgesehenen Lautsprecherausgang gehören.', 'An LS1/LS2 kommen die zwei Litzen des Lautsprecheradapters aus 9b. Beide Pads bleiben von MASSE, VCC, Kupplung und Schrauben getrennt.'),
('LoDi nennt R4/R5 im Lampen-/LED-Hinweis. R3/R6-Funktion und Bestückung der eigenen Revision sind nicht gesichert. Verzinnung ist kein Brückennachweis. Keines dieser Teile auf Verdacht ändern.', 'Du verwendest LoDi-514-LEDs, keine alten Glühlampen: R4/R5 nicht mit Lötzinn überbrücken. R3 und R6 nicht auslöten oder brücken. Die vier Plätze samt lesbarem Aufdruck fotografieren; fehlt die Bestückungszuordnung, Front-LEDs bis zur Bestätigung aus 11a abgetrennt lassen.'),
('Beschriftete Anschlussseite des eigenen Exemplars fehlt', 'Rote LoDi 511 umdrehen und die beschriftete Seite fotografieren'),
('Die wesentlichen Gleis-, Motor- und Frontanschlüsse sind im gezeigten Bild nicht beschriftet. Vor dem Löten die andere Seite mit lesbarer Revision und Anschlüssen dokumentieren. LoDi veröffentlicht solche Beschriftungen im Herstellerbeispiel; siehe Kapitel 9a. Das zweite rote Bild zeigt dieselbe sichtbare Ansicht, keinen Beleg der Rückseite.', 'Lege die stromlose, lose Platine ohne Decoder auf eine nichtleitende Unterlage. Fotografiere die ganze andere Seite senkrecht und zusätzlich Revision, Frontpads sowie SJ1/SJ2, falls vorhanden. Auf dem Foto müssen SW, RT, GE, MASSE, MOT_L, MOT_R, VCC, L_RT und L_WS lesbar sein. Ordne dann die Revision in 8a zu.'),
('STOPP - gleiche Jumpernamen können Verschiedenes bedeuten', 'Deine weiße V4.3: SJ2 unverändert lassen; rote LoDi 511 nach 8a zuordnen'),
('Die sichtbare weiße Wagenplatine hat SJ2 für Türbeleuchtung. Die LoDi-Motoranleitung beschreibt bei bestimmten Motorrevisionen SJ1/SJ2 als AUX-Auswahl. Diese Angaben nicht zwischen Platinen übertragen. Keine neue Brücke setzen, bevor die konkrete Motorrevision zugeordnet ist.', 'Auf deiner weißen MT-37700 V4.3 ist SJ2 mit Türbeleuchtung beschriftet. Dort nichts anlöten oder entfernen; es wird nicht zur Auswahl des Decoder-Ausgangs benutzt. Für das Innenlicht zählt nur die Jumperstellung der roten LoDi 511: lies sie nach 8a ab und notiere AUX4 oder AUX1. Keine Jumperstellung von der weißen auf die rote Platine übertragen.'),
('G1-STOPP bei ungeklärtem Ring', 'LoDi 511 noch nicht festschrauben, solange Ring A oder B ungeklärt ist'),
('Ohne eindeutige Zuordnung keine leitende Schraubmontage und keine Bestromung. Anfänger sollen keine eng benachbarten 21MTC-Pins mit freien Spitzen abtasten. Ein Piepton über unbekannte Bauteile ist kein Leiterbahnnachweis.', 'Beschrifte auf deinem Foto den Ring beim K1-Ende als A und den Ring beim Widerstands-/Frontende als B. Gib Fotos beider Seiten und die Revision an LoDi oder den Prüfenden. Lass für jeden Ring das elektrische Netz und die zulässige originale Schraubmontage bestätigen und in die Tabelle eintragen. Bis dahin Platine wieder abnehmen, Schrauben beiseitelegen, 60977 nicht einsetzen. Nicht mit freien Messspitzen im engen 21MTC-Feld suchen.'),
('Fachkundiger Ausweichweg: vollständig isolierende Halterung mit isolierter Schraubenführung auslegen. Vor Verdrahtung beide zugänglichen Ringe gegen positiv bestätigtes Chassis prüfen: kein leitender Montagekontakt. Kontaktierung vorher/nachher positiv bestätigen. Danach Radmasse über das dokumentierte MASSE-Pad verdrahten; dieser Pfad zum Chassis ist erwünscht. Eine Kunststoffscheibe nur oben genügt nicht. Maße und Passung sind offen; dies ist keine Halter-Kaufempfehlung.', 'Falls LoDi die originale Schraubmontage für deine Revision nicht bestätigt: Dem Fachbetrieb die unveränderte Platine und das 2976-Chassis geben. Auftrag: Halterung mit isolierter Schraubenführung herstellen; Ring A/B vor Verdrahtung gegen den positiv geprüften Metallrahmen isoliert nachweisen, jeweils mit Vor-/Nachprobe. Danach Radmasse separat am MASSE-Pad anschließen. Nur eine Unterlegscheibe unter dem Schraubenkopf genügt nicht, wenn Schaft oder Unterseite weiter Kontakt haben. Keine unbekannten Halter kaufen oder die Platine aufbohren.'),
('In dieser Fassung keine Anschlussfreigabe aus dem Namen ableiten; unbenutzt lassen, bis tatsächlich zugeordnet.', 'In deinem Aufbau nicht verdrahten. An PANTO, AUX3, AUX5 und S2 keine neue Litze oder Brücke setzen; vorhandene Bauteile nicht verändern.'),
('Orange im Herstellerbeispiel. Nicht interne 21MTC-Vcc oder Radmasse.', 'An diesen Front-VCC-Punkt kommt ausschließlich das bestätigte gemeinsame Plus des LoDi-514-Einsatzes. Kein Draht von dort zu MASSE oder Chassis.'),
('VCC und Jumper sind revisionsabhängig zu lesen', 'Vorn VCC/L_WS/L_RT benutzen; SJ1/SJ2 nur nach 8a ablesen'),
('LoDi-VCC für den beschriebenen Fronteinsatz ist nicht Pin 12 der 21MTC-Norm. Abweichende Plus-/Minus-schaltende Ausgänge nicht mischen. Bei Revisionen mit AUX-Wahl über SJ1/SJ2 niemals beide Brücken gleichzeitig setzen. SJ2 der weißen Wagenplatine hat eine andere Funktion.', 'Dein LoDi-514-Einsatz wird an den in dieser Tabelle benannten Standard-Frontanschlüssen betrieben: gemeinsames Plus an Front-VCC, Weiß an L_WS, Rot an L_RT. Zusätzliche positiv schaltende Anschlüsse einer neueren Motorplatine bleiben unbenutzt. Keine Leitung an 21MTC-Pin 12 löten. Für Innenlicht den in 8a notierten AUX-Ausgang verwenden; weiße Wagen-SJ2 nicht verändern.'),
('Artikelset und beigefügte Lautsprecher vergleichen. Nennimpedanz und erlaubte Last aus Herstellerunterlagen bestätigen; eine Gleichstrom-Widerstandsmessung allein ist kein Nennimpedanznachweis. Nur einen zum 60977 passenden Lautsprecher verwenden.', 'Nimm genau einen unveränderten Original-Lautsprecher aus deinem 60977-Satz. Unter den mitgelieferten Bauformen denjenigen wählen, dessen Schallkapsel ohne Druck in den freien LoDi-Lautsprecherbereich passt. Den zweiten nicht parallel anschließen. Ist die Herkunft des Lautsprechers nicht mehr eindeutig, erst Foto/Beipackteilbezeichnung klären; nicht aus einem Ohmmesswert auf seine Nennimpedanz schließen.'),
('Audioleitungen sind kein Masseanschluss', 'Am 60977-Lautsprecher gehen beide Drähte nur an LS1 und LS2'),
('Nennimpedanz und erlaubte Last aus Herstellerunterlagen bestätigen;', 'Bei nicht eindeutigem Originalteil die Nennimpedanz und erlaubte Last aus Herstellerunterlagen bestätigen;'),
('STOPP - LEDs nie unmittelbar ans Digitalgleis', 'Die zwei LoDi-514-Einsätze nicht an Gleis B/0 oder direkt an +Ub testen'),
('Kein Test direkt an Gleis, Trafo, Decoder-U+ oder einem unbekannten LED-Tester. Decoder-Dimmung ist kein Ersatz für Strombegrenzung. Auch eine sehr kurze falsche Verbindung kann eine LED zerstören.', 'Vorn kommt der Einsatz erst nach bestätigter LoDi-Strombegrenzung an VCC/L_WS/L_RT. Hinten erst nach Auswahl der zwei Serienwiderstände an +Ub/LV/LR. Bis dahin beide Einsätze abgetrennt lassen. Für die Diodenprobe aus 26 zuerst Prüfspannung und Prüfstrom deines Multimeters nachschlagen; sind sie unbekannt, diesen Test auslassen und Modul-/Datenblattabgleich aus 28 durchführen.'),
('Für die endgültige Widerstandsauslegung Zweigstruktur, zulässigen Betriebsstrom und minimale Zweigspannung klären. Eine gemessene Flussspannung sagt nichts über den erlaubten Maximalstrom aus. Bei fehlenden Daten LoDi bzw. einen Fachbetrieb die konkreten Einsätze charakterisieren lassen.', 'LoDi die Artikelnummer 514 sowie Fotos beider Seiten deiner zwei Einsätze geben. Benötigte Antwort je Weiß/Rot-Zweig: gemeinsame Plusbelegung, Reihen-/Parallelschaltung, zulässiger Betriebsstrom und kleinste anzusetzende Zweigspannung. Dazu nach dem passenden Vorwiderstand für 59649/+Ub bei deiner maximalen Decoder-Versorgung fragen. Antwort und Widerstandsbelastbarkeit in 11a eintragen. Eine Flussspannungsmessung liefert keinen zulässigen Maximalstrom.'),
('Dieses Beispiel ist KEINE Lötfreigabe', 'Für deinen hinteren Kopf noch keine 7,5-kΩ-Widerstände einlöten'),
('G3 bleibt bis zum ausgefüllten Stromnachweis offen', 'Zwei hintere Widerstände erst nach der LoDi-514-Antwort auswählen'),
('Die Zahlenbeispiele begründen weder eine Kauf- noch eine Lötfreigabe. Die zulässigen Daten der tatsächlichen LoDi-514-Einsätze sind hier noch nicht vollständig dokumentiert.', 'Trage für Weiß und Rot die Antwort aus Schritt 28 und die maximale Versorgung aus 29 ein. Berechne damit die beiden Widerstände nach 11; Wert, Toleranz und Belastbarkeit gehören in die Tabelle. Solange eine dieser Angaben fehlt, bleiben die hinteren LEDs vom 59649 getrennt. Vorn R4/R5 nicht zur Helligkeitsanpassung überbrücken.'),
('G1: vorhandenen Träger vorher abgleichen', 'Hinterer Märklin-Träger: +Ub nutzen, +5V/GND/SUSI frei lassen'),
('Beide Seiten, Index, Bestückung und Anschlüsse müssen mit der vorgesehenen Verwendung übereinstimmen. 59649 ist die MKL-Ausführung, trotzdem keine Freigabe allein durch mechanisches Passen. +5V ist mit eingesetztem ESU kein allein durch den Aufdruck bewiesener Versorgungswert. SUSI/60974 hinten nicht anschließen.', 'Lege den leeren Träger aus dem 60977-Satz wie die Zeichnung hin: Lautsprecherbuchse links, LV/+Ub/MR/MV/0/GL/B/GR unten. Gleiche jeden dieser Aufdrucke ab. Benutze hinten nur +Ub, LV, LR, B/GR und 0/GL. +5V, GND und beide Steckbuchsen bleiben frei; unbenutzte Litzen einzeln isolieren. Danach Indexposition von Träger und 59649 vergleichen. Weicht eine Beschriftung ab, beide Trägerseiten fotografieren und den ESU noch nicht aufstecken.'),
('Physischer Ausgang ist nicht die Lage am Zug', 'Hinten Rot an LV und Weiß an LR; keine zweite Richtungsumkehr einstellen'),
('LV heißt Licht vorne des Decoders, nicht weißes Licht an jeder Zugnase. Durch die entgegengesetzte Einbaulage muss bei dieser festen Mappingvariante hinten Rot an LV liegen. Nicht zusätzlich unkontrolliert Fahrtrichtung oder Mapping invertieren.', 'Für diese eine Verdrahtung muss im 59649 gelten: F0 vorwärts schaltet LV, F0 rückwärts schaltet LR. Deshalb den roten Zweig über seinen Widerstand an LV und den weißen über seinen Widerstand an LR anschließen. Nicht zusätzlich eine Richtungsumkehr aktivieren. Bei vorwärts und Fahrstufe 0 muss die Motorseite weiß, die motorlose Seite rot leuchten; Prüfung erst in 54.'),
('Anschlussvariante vor Löten kontrollieren', 'Deine weißen Wagenplatinen: RT an O, GE an L, B frei'),
('LoDi beschreibt auch eine andere Anschlussvariante mit anderer O/B-Zuordnung. Diese hier nicht mischen. Bei der weißen V4.3 darf SJ2 nicht als Motor-AUX-Auswahl interpretiert werden. Bestehende Radmassefedern in den Wagen gemäß bestätigtem zweipoligen LoDi-Aufbau entfernen; die Radkontakte der Triebköpfe bleiben erforderlich.', 'An jeder weißen MT-37700 V4.3 gehen beide RT-Kupplungslitzen an O, beide GE-Litzen an L. B bleibt an beiden Enden ohne Anschluss. SJ2/Türbeleuchtung unverändert lassen. Falls der Mittelwagen eine Radkontaktfeder besitzt, zuerst deren Verbindung zum Beleuchtungspfad prüfen und nur diese Kontaktfeder entsprechend dem LoDi-Aufbau entfernen; keine Achshalterung ausbauen. Radkontakte beider Triebköpfe erhalten.'),
('Nur ein freigegebener Stromkreis', 'Gesamten ICE nur auf ein und denselben CS3-Stromkreis stellen'),
('Der RT-Bus verbindet beide Schleifer. Kein Überbrücken von Haupt-/Programmierausgang, Gleisanschlussbox und CS3 oder verschiedenen Boosterkreisen zulassen. Vor Umstecken immer abschalten und elektrische Trennung herstellen.', 'RT verbindet den Schleifer im Motortriebkopf mit dem im motorlosen Kopf. Deshalb muss der ganze Zug auf einem einzigen CS3-Stromkreis stehen: kein Kopf auf dem Programmiergleis und der andere auf der Anlage. Gleisanschlussbox und Programmer bleiben abgetrennt. Vor jedem späteren Wechsel auf ein anderes Gleis den ganzen Zug abheben beziehungsweise den vollständigen Aufbau stromlos umsetzen.'),
('Diese OL-Tabelle ist keine Regel für bestückte LoDi-Leisten', 'Nach Anschluss einer weißen LoDi-Leiste nicht L gegen O auf OL zwingen'),
('Die Wagenplatine enthält absichtlich Elektronik zwischen den Versorgungswegen. Kein Bauteil und keine Leiterbahn entfernen, um für diese Tabelle ein OL zu erzwingen. Weiter mit 14b.', 'Prüfe 14a nur an den freien Kupplungslitzen ohne angeschlossene Wagenplatine. Sobald deine weiße LoDi-Leiste angeschlossen ist, arbeite nach 14b: dort RT-Kontakt zu O und GE-Kontakt zu L messen. Einen Zahlenwert zwischen L und O nicht durch Auftrennen einer Leiterbahn beseitigen. Richtig zugeordnete L/O-Pads und unbeschaltete B-Pads beibehalten.'),
('Leiste stromlos ohne weitere Verbindungen prüfen: Revision, Aufdrucke L/O/B und Betriebsart dokumentieren. L-Ende A zu L-Ende B sowie O-Ende A zu O-Ende B müssen als vorgesehene Durchleitungen bestätigt werden. Elektronische Querpfade und Messrichtung dokumentieren; bei unklarer Zuordnung fachkundig klären.', 'An deiner noch nicht verdrahteten weißen MT-37700 V4.3 beide Enden mit A/B beschriften. Eine Messspitze an L am Ende A, die andere an L am Ende B: Wert notieren. Danach O-A gegen O-B messen. Kontakte positiv vor/nachprüfen; die L-L- und O-O-Durchleitungen müssen stabil sein. Anschließend L gegen O in beiden Messrichtungen nur als Ausgangswert notieren. Bei unklarer Durchleitung Foto der beiden Messpunkte und Messwert zur Prüfung geben; noch keine Kupplungslitze anlöten.'),
('STOPP - dieser Anschluss ist noch nicht freigegeben', 'Beide vorhandenen 60974 jetzt abgesteckt lassen'),
('Die sichtbare rote LoDi-Motorplatine zeigt keine belegte SUSI-Buchse. K1, die drei runden Lötaugen am Frontende und die kleinen Durchkontaktierungen dürfen nicht als Pufferanschluss erraten werden. Für die folgenden ersten Funktionstests bleibt der 60974 abgesteckt.', 'In diesem Bauabschnitt wird keiner deiner zwei 60974 angeschlossen. K1, S2 und VCC der roten LoDi 511 sind kein hier bestätigter vierpoliger Pufferanschluss. Den Pufferstecker nicht abschneiden. Gib LoDi Fotos beider Seiten und die Revision mit der Frage nach einem unveränderten, zulässigen SUSI-Anschluss für 60974 am 60977. Erst nach dem in 42-44 beschriebenen Nachweis einen Puffer vorn ergänzen; hinten keinen.'),
('Motorpufferung zuletzt testen', '60974-Motorpufferung erst nach freier Teststrecke aktivieren'),
('Der erste Synchronisationsversuch gehört nicht mehr hierher', 'Vor Schritt 45 muss dein C-Protokoll bestanden sein'),
('Für den eingebauten 60941-HLA passenden Motortyp anhand der Märklin-Unterlagen wählen. Prüfstand-Motoreinstellungen nicht blind übernehmen.', 'Am 60977 für deinen eingebauten 60941 den Motortyp Hochleistungsantrieb C90 wählen; die Märklin-Tabelle ordnet ihm CV 52 = 3 zu. Einstellung rücklesen. Nicht Glockenanker oder Softdrive Sinus übernehmen, die eventuell zum Prüfstand gehörten.'),
('Eine freie Funktion wählen, die keinen benötigten Sound überschreibt. AUX-/Jumper-Zuordnung anhand der tatsächlichen LoDi-Motorrevision festlegen. Nicht automatisch AUX4 oder AUX1 unterstellen und nie beide Auswahlbrücken gleichzeitig setzen.', 'Nimm den in 8a notierten Ausgang: AUX4 bei bestätigter älterer Zuordnung oder allein geschlossenem SJ1, AUX1 bei allein geschlossenem SJ2 der Motorrevision ab 1.50. Im 60977-Projekt diesen Ausgang auf eine bisher freie Funktionstaste legen und Innenlicht nennen; in beiden Fahrtrichtungen sowie Stand/Fahrt aktivieren. Tastennummer hier notieren: _____. Kein Soundmapping dafür überschreiben. Die Jumper bleiben unverändert.'),
('Vor Spannung: drei Freigaben müssen vorliegen', 'Vor Schritt 52: C-Protokoll, Motorprüfung und Anschlusskarten abhaken'),
('Keine automatische Motoreinmessung auf kurzem Gleis', 'Auf deinem kurzen Prüfgleis niemals CV 7/Firmware-Feld auf 77 setzen'),
('Der Märklin-Einmesslauf kann stark beschleunigen. Er gehört auf eine dafür geeignete freie Strecke gemäß Herstelleranleitung. Ein kurzer Prüfgleisabschnitt ist dafür ausdrücklich nicht geeignet.', 'Für die Prüfungen 52-56 keine Einmessfahrt anfordern. Den 60977 mit dem eingestellten C90-Motortyp nur kontrolliert bei kleiner Fahrstufe bewegen. Die automatische Einmessfahrt bleibt außerhalb dieses kurzen Prüfaufbaus; sie darf nach Aktivierung durch den nächsten Fahrbefehl bis zur Höchstgeschwindigkeit beschleunigen.'),
('Für Strom im Digitalgleis und gepulsten Ausgängen geeignete Messtechnik verwenden. Eine einfache Multimeteranzeige ist je nach Messprinzip nur ein Mittelwert, keine sichere Spitzenstromfreigabe. Bei fehlender Erfahrung die Belastungsprüfung fachkundig durchführen lassen.', 'Vor dem Messversuch dem Fachbetrieb die Anzahl deiner Mittelwagen und das Schema aus 14 geben. Prüfauftrag: Gesamtlast mit Motor, Sound und Innenlicht sowie Last/Spannungsabfall des RT-Kupplungswegs bei alleiniger Einspeisung von hinten bestimmen; Decoder- und Kupplungsgrenzen getrennt bewerten. Ohne dafür geeignetes Messgerät keine eigene A/mA-Messung am Gleis starten. Ein kleiner Ohmwert ersetzt diesen Lasttest nicht.'),
('Regulärer Halt ist ein Fahrbefehl, keine Stromtrennung', 'Am roten Signal muss deine CS3 dem ICE Fahrstufe 0 senden'),
('Klare Grenze für Einsteiger', 'Unklarer Kontakt am 2976: Foto und konkrete Messreihe statt Einschaltversuch'),
('Wenn du die beiden Enden eines Bauteils, einen 21MTC-Kontakt oder einen Messwert nicht sicher zuordnen kannst: nicht weiterlöten und keine Probe unter Spannung. Detailfoto mit Markierung und Messwert anfertigen; genau diesen Arbeitsschritt prüfen lassen. Eine Schutzschaltung ersetzt diese Prüfung nicht.', 'Lass den 60977 beziehungsweise 59649 abgezogen. Auf einem scharfen Foto beide verwendeten Messpunkte markieren und die Kapitel-/Schrittnummer, Messbereich, Vorprobe, Messwert und Nachprobe dazuschreiben. Genau diese Angaben zur Prüfung geben. Erst nach bestätigter Kontaktzuordnung dieselbe vollständige Messreihe wiederholen; nicht zwischendurch am Gleis ausprobieren.'),
]

def install(ns):
    old_p = ns['p']
    hits = {before: 0 for before, _ in REPLACEMENTS}
    ns['REV7_HITS'] = hits

    def concrete_p(text, style='body'):
        for before, after in REPLACEMENTS:
            if before in text:
                hits[before] += text.count(before)
                text = text.replace(before, after)
        return old_p(text, style)

    ns['p'] = concrete_p
    old_page = ns['page']

    def page(title):
        if title == 'A. Decoder-Nachweis: Ausstattung und Grenzen':
            add_case_page(ns, old_page)
        if title == '9. Platinenbefestigung: sichere Freigabe':
            add_jumper_page(ns, old_page)
        return old_page(title)

    ns['page'] = page

def add_case_page(ns, page):
    page('0. Diese Teile kommen an diese Stelle')
    ns['add']('Nur dein analoger ICE 1 aus HOBBY-Startpackung 2976 wird nach dieser Fassung bearbeitet. Die Teile für den Delta-ICE 33701 und den ICE 2 getrennt lassen. Motortriebkopf bedeutet hier der Kopf mit dem 60941-Motor; motorloser Kopf ist das entgegengesetzte Zugende.')
    ns['table'](['Ort / vorhandenes Teil', 'Was du in genau diesem Aufbau damit machst'], [
        ('Motortriebkopf: 60941 + 60977 + LoDi 511', '60941 ersetzt den Feldspulenmotor. 60977 sitzt auf der roten LoDi 511 und steuert Motor, Sound, vordere Front-LED und Wagen-Innenlicht.'),
        ('Motorloser Kopf: ESU 59649 + Träger aus 60977', '59649 kommt auf den separaten Märklin-Träger. Er schaltet nur die hinteren Front-LEDs. Seine Motor- und unbenutzten AUX-Leitungen einzeln isolieren.'),
        ('Beide Köpfe: je ein LoDi-514-Frontteil', 'Vorn an die bestätigten LoDi-Frontpads. Hinten an +Ub sowie über je einen eigenen Widerstand an LV/Rot und LR/Weiß; siehe 12a.'),
        ('Mittelwagen: weiße MT-37700 V4.3', 'Je Wagen RT an beide O-Pads, GE an beide L-Pads; B-Pads frei. Platine leitet längs durch. Nur kurze Litzen von den Kupplungen zu den Pads anschließen.'),
        ('SJ2 auf der weißen Wagenplatine', 'Nicht verändern. Die Brücke betrifft die Türbeleuchtung, nicht den Decoder-Ausgang für das Wagenlicht.'),
        ('Beide Schleifer / beide Radkontakte', 'Schleifer über RT verbinden. Jeder Triebkopf behält seine eigene Radmasse. Hinten GE nicht an einen Decoder-Ausgang anschließen.'),
        ('Zwei vorhandene Märklin 60974', 'Für die ersten Tests beide abgesteckt lassen. Später höchstens einen am vorderen 60977 nach gesondertem Anschlussnachweis ergänzen.'),
    ], [2.3, 4.3])
    ns['warn']('Jetzt zuerst: Decoder-Nachweis und Bauteilfotos', 'Bevor du Motor oder Altplatine aus dem 2976 ausbaust, Kapitel A-C erledigen. Lose vorhandene Platinen darfst du stromlos fotografieren und die Aufdrucke aus 8a/9a ablesen. Am zusammengesteckten Zug noch nichts anlöten. Die nachfolgenden Einbauschritte gelten erst nach bestandenem C-Protokoll.')

def add_jumper_page(ns, page):
    page('8a. Deine LoDi-Jumper: ablesen, nicht umbauen')
    ns['add']('Eine Lötbrücke ist hier eine sichtbare metallische Verbindung zwischen den beiden dafür vorgesehenen Kontaktflächen. Die folgende Tabelle benutzt die vorhandene Stellung. Du setzt keine zusätzliche Brücke und entfernst keine Leiterbahn. Beide Decoder bleiben zum Ablesen abgezogen.')
    ns['table'](['Bauteil / tatsächlich abgelesener Zustand', 'Was gilt für deinen Aufbau', 'Dein Handgriff'], [
        ('Weiße MT-37700 V4.3: SJ2 mit Aufdruck Türbeleuchtung', 'SJ2 betrifft die Tür-LEDs dieser Wagenplatine. Es wählt weder AUX1 noch AUX4.', 'Vorhandenen Zustand fotografieren und unverändert lassen. RT/O und GE/L werden davon nicht umbenannt.'),
        ('Rote LoDi 511: bestätigte V1.49, keine SJ1/SJ2-Auswahl', 'In der dokumentierten älteren Motorzuordnung wird Innenlicht über AUX4 geschaltet.', 'Aufdruck und Layout mit Herstellerbeispiel abgleichen; bei bestätigter Übereinstimmung AUX4 notieren. Keine Brücke nachrüsten.'),
        ('Rote Motorplatine ab V1.50: nur SJ1 geschlossen', 'GE/Wagenlicht wird über AUX4 geschaltet.', 'AUX4 notieren; SJ1 und den offenen SJ2 unverändert lassen.'),
        ('Rote Motorplatine ab V1.50: nur SJ2 geschlossen', 'GE/Wagenlicht wird über AUX1 geschaltet.', 'AUX1 notieren; SJ2 und den offenen SJ1 unverändert lassen.'),
        ('Rote Motorplatine ab V1.50: beide offen', 'Für diese Stellung ist hier kein geschlossener Innenlicht-Auswahlpfad bestätigt.', 'Nichts brücken. Revision und Nahfoto beider Felder an LoDi geben; Anschluss-/Konfigurationsantwort abwarten.'),
        ('Rote Motorplatine ab V1.50: beide geschlossen', 'Die beiden Decoder-Ausgänge können verbunden werden; Decoder-Schaden möglich.', '60977 abgezogen lassen. Nicht einschalten und keine Brücke auf Verdacht entfernen; diese Platine LoDi zur Korrektur vorlegen.'),
        ('Revision unlesbar, andere Version oder Stellung unklar', 'Noch keine Zuordnung für deine tatsächliche Motorplatine.', 'Ganze beschriftete Seite und beide Felder scharf fotografieren. Bis zur revisionsbezogenen Bestätigung keinen AUX-Wert eintragen.'),
    ], [2.1, 2.0, 2.5])
    ns['add']('<b>Dein Eintrag für Schritt 48:</b> rote Platine Revision ______; SJ1 ______; SJ2 ______; bestätigter Innenlicht-Ausgang ______. Auf dem weißen Wagen-SJ2 wird hierfür nichts geändert.')
    ns['warn']('Nur sehen ist noch kein elektrischer Brückennachweis', 'Ist die Trennfuge zwischen zwei Jumperflächen verdeckt oder sieht sie nur glänzend aus, keinen Zustand raten. Makrofoto mit seitlichem Licht aufnehmen und mit dem Hersteller klären. Kein Multimeter-Piepton über eine bestückte Platine ersetzt automatisch die Zuordnung dieser Brücke.')
    ns['refs'](3, 4)
