"""Resolve remaining generic execution wording without fabricating device-specific facts."""
from pathlib import Path

MORE = [
('Deine weißen Wagenplatinen: RT an O, GE an L, B frei', 'Deine Wagenplatinen: RT an O, GE an L, optionale Radmasse an B'),
('Richtig zugeordnete L/O-Pads und unbeschaltete B-Pads beibehalten.', 'L/O-Zuordnung beibehalten; B nur bei der Radmasseoption aus 14c anschließen.'),
('Für den gemeinsamen Versuch müssen beide Decoder sicher getrennte Lasten tragen. Eignung von 21MTC, AUX-Pegeln und Lasten vorher bestätigen.', 'Dem Prüfenden beide Artikelnummern geben. Er muss je Aufnahme Steckschnittstelle, Motor und Lautsprecherlast benennen und die Eignung für genau diesen Decoder bestätigen; keinen ungeprüften Prüfstand kaufen.'),
('Gleis-Digitalspannung und gepulste Funktionsspannung sind keine gewöhnliche Sinus-AC-Spannung. Ein einfacher AC-Multimeterwert am Gleis oder PWM-Ausgang ist nicht automatisch der Maximalwert für diese Rechnung. Geeignete Messung und eingestellte Versorgungsspannung dokumentieren.', 'Für den hinteren 59649 die maximale Versorgung des LED-Zweigs durch den Prüfenden bestimmen lassen: verwendete CS3/Netzteilkonfiguration, Messpunkte am bestätigten Prüfaufbau, Messgerät und gemessenen Spitzenwert notieren. Nicht selbst mit freien Spitzen zwischen 21MTC-Pins messen. Ein einfacher AC-Wert am Gleis ist kein Ersatz; die Spannung an O/RT ist nicht automatisch die Spannung am LED-Zweig.'),
('Jeden Widerstand in seinen eigenen Weiß-/Rot-Zweig setzen. Drähte einzeln isolieren, Widerstandskörper mechanisch und thermisch geeignet befestigen; nicht direkt gegen Kunststoff oder LED drücken. Strombegrenzung prüfen, bevor der ESU eingesetzt wird.', 'Am hinteren Kopf den bestätigten Rot-Widerstand in die Litze nach LV und den Weiß-Widerstand in die Litze nach LR löten. Beide Drahtanschlüsse einzeln isolieren; den Widerstandskörper mit Abstand zu LED, Gehäuse und Nachbarlitzen halten, nicht gegen Kunststoff drücken. Widerstandswerte vor Anschluss an den ESU einzeln nachmessen und notieren.'),
('Alte Lampenfassung nicht weiter elektrisch nutzen. Schleifer/Radmasse vorher zuordnen. Die neue Plusleitung darf keine Feder- oder Schraubverbindung zum Chassis haben.', 'Die alte Lampenfassung von der bisherigen Lichtschaltung ablöten und nicht als Lötstütze verwenden. Die neue Leitung direkt von +Ub zum bestätigten Plusanschluss des hinteren LoDi-514-Einsatzes führen. Keine alte Lampenfeder, Masseöse oder Chassisschraube als Zwischenanschluss benutzen. Schleifer- und Radmasseleitungen getrennt beschriftet erhalten.'),
('Bei bestückter Leiste ist ein endlicher Messwert zwischen L/O nicht automatisch ein Fehler und OL kein pauschaler Pflichtwert. Mit dokumentiertem beziehungsweise fachkundig bestätigtem Platinenverhalten vergleichen. Auffällige Abweichung: Anschlusslitzen zur Eingrenzung wieder lösen, nicht die LoDi-Leiterbahn schneiden.', 'Vergleiche den jetzt gemessenen L/O-Wert nur mit der vor dem Anlöten dokumentierten Leiste bei gleicher Messrichtung und gleichem Messbereich. Neu niederohmig geworden: Kupplungslitzen wieder abtrennen und diese allein nach 14a prüfen; nach sichtbaren Lötbrücken suchen. Bei verbleibender Abweichung die Leiste mit Vorher-/Nachherwert an LoDi geben. Kein Bauteil entfernen und keine Leiterbahn trennen, um OL zu erhalten.'),
('Ohne Puffer und Wagenbus beginnen. Vor Spannung Fahrstufe 0 einstellen; Bewegung erst in Schritt 53. Gehäuse offen lassen, lose Leiter sichern. Nach Herstellerverfahren am getrennten Programmiergleis prüfen, danach am geeigneten Betriebsgleis mfx, F0 und leisen Sound kontrollieren. Programmierung ist kein Isolationstest.', 'Nur den Motortriebkopf aufstellen; Dummy und Wagen bleiben auf dem Tisch. 60974 abgesteckt, Kupplung frei, lose Litzen einzeln isoliert. 60977 sitzt nach 9c; Motorprüfung und Front-Strombegrenzung sind bestanden, Lautsprecher nur an LS1/LS2. Fahrstufe 0, CS3-Automatik aus. Erst am getrennten Programmiergleis nach Märklin prüfen; danach nur den ganzen Kopf stromlos auf das Betriebsgleis umsetzen. Dort F0 und Richtung im Stand, dann leisen Sound prüfen. Noch keine Fahrt.'),
('Nur bei gesichertem Fahrzeug und genügend Fahrweg eine kleine Fahrstufe kurz anlegen, dann auf Null. Bei Brummen ohne Bewegung, Geruch, Überlast oder ungewöhnlicher Erwärmung sofort abschalten. Nicht den Rotor blockiert halten, um einen Grenzstrom zu ermitteln.', 'Gleis waagerecht mit ausreichend freiem Fahrweg gegen Absturz sichern. Nur kleinste Fahrstufe kurz anlegen und wieder auf 0 stellen; nicht Motor oder Räder festhalten. Bei Brummen ohne Fahrt sofort Gleisversorgung aus; Bürstensitz, Mechanik und 6a erneut prüfen. Bei falscher Fahrtrichtung Motorzuordnung nach 9a korrigieren, nicht zusätzlich das Licht umkehren. Bei Geruch oder Überlast abschalten, keinen zweiten Versuch starten.'),
('Alle vorgesehenen Wagen mit der späteren Helligkeit prüfen; Motorfahrt und Sound zusätzlich berücksichtigen. Dann bei geeigneter Sicherung die Einspeisung über jeweils nur einen Schleifer prüfen. Anschlussänderungen ausschließlich spannungslos, keine Metallstücke unter Schleifer klemmen.', 'Den in 57 beschriebenen Lasttest erst mit der endgültigen Wagenzahl und Helligkeit durchführen lassen. Für Einzel-Schleiferbetrieb muss der Prüfende jeweils eine Schleiferzuleitung im stromlosen Aufbau gezielt abtrennen und einzeln isolieren; anschließend den geprüften Aufbau versorgen. Keine Leitung unter Spannung abziehen und kein Metallstück unter den Schleifer schieben. Nach jedem Umbau Sollverbindungen kontrollieren.'),
('Kontakt dem aktiven ICE-Ablauf zuordnen. Bei Halt am zugehörigen Signal sendet er einen langsamen Annäherungsbefehl; ein Haltemelder davor sendet Fahrstufe 0 an genau diesen ICE. Restbremsweg berücksichtigen. Bei passendem Fahrtbegriff und freiem Fahrweg darf dieser Haltablauf nicht stoppen. Unklare Freigabe ist kein Abfahrauftrag.', 'Vor der Ereigniserstellung je Richtung Signalname/-adresse, Brems- und Haltekontaktadresse, Abstand zum Schutzpunkt und diesen einen ICE-Eintrag notieren. Diese konkreten Anlagendaten fehlen noch. Erst daraus den Ablauf erstellen: bei Signalhalt langsame Annäherung am Bremskontakt und Fahrstufe 0 am Haltekontakt für genau diesen ICE. Bis dieser Ablauf abgenommen ist, den Zug von Hand über die CS3 anhalten; ein rotes Signal allein genügt nicht.'),
('Die Handlung hängt an den Endpunkten, nicht an Farbe oder Position', 'Am 60941 bleibt nur der Kondensator zwischen den beiden Bürstenfahnen'),
('Bauteil von Bürste zu Metallrahmen: im vorgesehenen Umbau entfernen. Bauteil zwischen beiden Bürsten: Quer-Kondensator. Bei verdecktem Ende erst freilegen oder prüfen lassen. Nie nach dem Foto blind Drähte abschneiden. OL kann auch trotz unerwünschtem Masse-Kondensator erscheinen.', 'Beide Lötenden am eingebauten 60941 mit der Lupe verfolgen. M1-M2: Kondensator belassen. Bürstenfahne zu Metallrahmen/Masseöse: diesen Kondensator auslöten, die Radmasseleitung erhalten. Verschwindet ein Draht unter dem Motorschild, Detailfoto für die Zuordnung anfertigen, nicht abschneiden. Anschließend die vollständige Messfolge 6a wiederholen.'),
('Ist das nicht möglich, diese Prüfung fachkundig durchführen lassen.', 'Gibt es keinen sicheren Austritt für die isolierten Hilfsenden, den Kopf offen lassen und dem Prüfenden die konkrete Klemm-/Austrittsstelle fotografieren. Nicht das Gehäuse auf die Messleitungen drücken.'),
('Verbindlicher Dokumentstatus', 'Vor dem tatsächlichen Umbau noch zu erledigen'),
('REV7 ist eine Prüffassung, nicht das Versprechen eines vollständig risikofreien Umbaus. Ohne G0, reale Platinenzuordnung und bestandene Einzelprüfungen keine Gesamtfreigabe. Keine erfundenen Messwerte, Hardwaretests oder vollständigen externen Konsilvoten sind in diesem Dokument enthalten.', 'Zuerst A-C mit deinen beiden Decodern bestehen. Danach eigene LoDi-Revision/Index, Befestigungsringe, Front-LED-Daten und originale Kupplungspassung anhand der genannten Fotos und Messungen bestätigen. Die konkrete Arbeitsfassung setzt diese Ergebnisse nicht voraus. Der Zug wurde für diese Anleitung nicht physisch gemessen; vollständiger externer Abschlussbericht weiterhin ausstehend.'),
]

def install(ns):
    path=Path(__file__).resolve().parent/'rev7_additions.py'
    code=path.read_text().replace(')],320))',')],245))')
    # Avoid a source-only continuation page in the already complete flicker test.
    code=code.replace("ns['refs'](1,3,4,23)\n", "ns['refs'](23)\n")
    scope={'__file__':str(path)}
    exec(compile(code,str(path),'exec'),scope)
    scope['EXTRA'].extend(MORE)
    scope['install'](ns)
    ns['SOURCES'][1]=('Märklin','Nachrüstdecoder 60975/60976/60977','Stand 10/2025; S. 3-7, 13, 17 und 19: Einbau, Funktionen, C90-Motortyp und Grenzen','https://static.maerklin.de/damcontent/f5/a9/f5a967e35e5b3faa19d17d36c62f586a1762409392.pdf')
